//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Analysis_Laboratory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical_Analysis_Laboratory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2148748915_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_2148748915_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_test {
            get {
                object obj = ResourceManager.GetObject("add test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_User1 {
            get {
                object obj = ResourceManager.GetObject("Add_User1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back_Arrow_60px {
            get {
                object obj = ResourceManager.GetObject("Back_Arrow_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back_Arrow_60px1 {
            get {
                object obj = ResourceManager.GetObject("Back_Arrow_60px1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string CaptionErrorActionData {
            get {
                return ResourceManager.GetString("CaptionErrorActionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string CaptionQuitionAddData {
            get {
                return ResourceManager.GetString("CaptionQuitionAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string CaptionQuitionDeleteData {
            get {
                return ResourceManager.GetString("CaptionQuitionDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انهاء.
        /// </summary>
        internal static string CaptionQuitionEndExam {
            get {
                return ResourceManager.GetString("CaptionQuitionEndExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string CaptionQuitionUpdateData {
            get {
                return ResourceManager.GetString("CaptionQuitionUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string CaptionSaveData {
            get {
                return ResourceManager.GetString("CaptionSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح.
        /// </summary>
        internal static string CaptionSuccessActionData {
            get {
                return ResourceManager.GetString("CaptionSuccessActionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيه.
        /// </summary>
        internal static string CaptionWarningData {
            get {
                return ResourceManager.GetString("CaptionWarningData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical_Analysis_Laboratory.
        /// </summary>
        internal static string DataBaseName {
            get {
                return ResourceManager.GetString("DataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال جميع البيانات.
        /// </summary>
        internal static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! حقل البحث فارغ.
        /// </summary>
        internal static string EmptyDataSerarch {
            get {
                return ResourceManager.GetString("EmptyDataSerarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد سجلات محددة .
        /// </summary>
        internal static string EmptySelectdData {
            get {
                return ResourceManager.GetString("EmptySelectdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;C&quot; لا يمكن وضع النسخة على القرص .
        /// </summary>
        internal static string ErrorSaveBackupIndesk_C {
            get {
                return ResourceManager.GetString("ErrorSaveBackupIndesk_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap homepage {
            get {
                object obj = ResourceManager.GetObject("homepage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_add_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_add_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_add_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Add_Male_User_Group_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_Add_Male_User_Group_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Admin_Settings_Male_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_Admin_Settings_Male_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_blood_sample_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_blood_sample_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_bookmark_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_bookmark_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_bookmark_38px {
            get {
                object obj = ResourceManager.GetObject("icons8_bookmark_38px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_box_important_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_box_important_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_calendar_31_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_calendar_31_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cancel_32px_2 {
            get {
                object obj = ResourceManager.GetObject("icons8_cancel_32px_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Checkmark_32px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_Checkmark_32px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_close_window_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_close_window_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Combo_Chart_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_Combo_Chart_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Delete_Trash_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_Delete_Trash_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Delete_Trash_60px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_Delete_Trash_60px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_department_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_department_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_edit_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_edit_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_edit_60px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_edit_60px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_error_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_error_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_filter_and_sort_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_filter_and_sort_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_flow_chart_50px_2 {
            get {
                object obj = ResourceManager.GetObject("icons8_flow_chart_50px_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_high_priority_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_high_priority_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_home_40px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_home_40px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_home_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_home_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_home_60px_5 {
            get {
                object obj = ResourceManager.GetObject("icons8_home_60px_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_knowledge_sharing_40px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_knowledge_sharing_40px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_login_60px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_login_60px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_login_rounded_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_login_rounded_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_logout_40px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_logout_40px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_logout_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_logout_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_macos_close_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_macos_close_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_maybe_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_maybe_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_medical_history_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_medical_history_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_nurse_call_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_nurse_call_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_nurse_call_60px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_nurse_call_60px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ok_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_ok_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_open_in_popup_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_open_in_popup_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_password_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_password_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_save_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_save_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_save_close_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_save_close_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_schedule_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_schedule_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_schedule_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_schedule_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_schedule_60px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_schedule_60px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_scorecard_38px {
            get {
                object obj = ResourceManager.GetObject("icons8_scorecard_38px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_search_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_search_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Session_Timeout_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_Session_Timeout_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Sync_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_Sync_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_test_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_test_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_test_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_test_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Time_Machine_38px {
            get {
                object obj = ResourceManager.GetObject("icons8_Time_Machine_38px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_upload_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_upload_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_upload_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_upload_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_user_locked_40px {
            get {
                object obj = ResourceManager.GetObject("icons8_user_locked_40px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_users_50px_2 {
            get {
                object obj = ResourceManager.GetObject("icons8_users_50px_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_users_60px {
            get {
                object obj = ResourceManager.GetObject("icons8_users_60px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_view_schedule_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_view_schedule_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_view_schedule_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_view_schedule_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_xbox_menu_40px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_xbox_menu_40px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_xls_export_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_xls_export_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_xls_export_50px_1 {
            get {
                object obj = ResourceManager.GetObject("icons8_xls_export_50px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loginBG {
            get {
                object obj = ResourceManager.GetObject("loginBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Medical_Analysis_LaboratoryLogo {
            get {
                object obj = ResourceManager.GetObject("Medical_Analysis_LaboratoryLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تحديد السجل المطلوب.
        /// </summary>
        internal static string NotUpdateProductdefcult {
            get {
                return ResourceManager.GetString("NotUpdateProductdefcult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الإضافة بالتأكيد.
        /// </summary>
        internal static string QuitionAddData {
            get {
                return ResourceManager.GetString("QuitionAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الحذف بالتأكيد.
        /// </summary>
        internal static string QuitionDeleteData {
            get {
                return ResourceManager.GetString("QuitionDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد انهاء الاختبار بالتأكيد.
        /// </summary>
        internal static string QuitionEndExam {
            get {
                return ResourceManager.GetString("QuitionEndExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد التعديل بالتأكيد.
        /// </summary>
        internal static string QuitionUpdateData {
            get {
                return ResourceManager.GetString("QuitionUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESKTOP-PH4H08Q.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح.
        /// </summary>
        internal static string SuccessAddData {
            get {
                return ResourceManager.GetString("SuccessAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        internal static string SuccessDeleteData {
            get {
                return ResourceManager.GetString("SuccessDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تصد ير البيانات بنجاح.
        /// </summary>
        internal static string SuccessExportData {
            get {
                return ResourceManager.GetString("SuccessExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت استعادة النسخة الاحتياطية بنجاح.
        /// </summary>
        internal static string SuccessRestoreBackup {
            get {
                return ResourceManager.GetString("SuccessRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اجراء النسخة الاحتياطية بنجاح.
        /// </summary>
        internal static string SuccessSaveBackup {
            get {
                return ResourceManager.GetString("SuccessSaveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعد يل بنجاح.
        /// </summary>
        internal static string SuccessUpdateData {
            get {
                return ResourceManager.GetString("SuccessUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Timeline {
            get {
                object obj = ResourceManager.GetObject("Timeline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيم المجال غير صحيحة.
        /// </summary>
        internal static string WarningBValBiggerThanEVal {
            get {
                return ResourceManager.GetString("WarningBValBiggerThanEVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم حذف التحاليل المتعلقة 
        ///بهذة الزيارة.
        /// </summary>
        internal static string WarningClrearVisitTests {
            get {
                return ResourceManager.GetString("WarningClrearVisitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات .
        /// </summary>
        internal static string WarningDataIsEmpty {
            get {
                return ResourceManager.GetString("WarningDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تحديد السجل المطلوب.
        /// </summary>
        internal static string WarningIdSelectData {
            get {
                return ResourceManager.GetString("WarningIdSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تقم بتغيير كلمة السر.
        /// </summary>
        internal static string WarningInputAlreadyPassword {
            get {
                return ResourceManager.GetString("WarningInputAlreadyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادخال ارقام فقط.
        /// </summary>
        internal static string WarningInputJustNumber {
            get {
                return ResourceManager.GetString("WarningInputJustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة قصيرة جدا.
        /// </summary>
        internal static string WarningInputPasswordlesslenth {
            get {
                return ResourceManager.GetString("WarningInputPasswordlesslenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تحديد المسار اولاً.
        /// </summary>
        internal static string WarningInputPathToBackup {
            get {
                return ResourceManager.GetString("WarningInputPathToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر خاطئة.
        /// </summary>
        internal static string WarningInputvalidPassword {
            get {
                return ResourceManager.GetString("WarningInputvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادخال قيمة اقل من 20.
        /// </summary>
        internal static string WarningInputValueInRange {
            get {
                return ResourceManager.GetString("WarningInputValueInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تحديد العقدة الأب.
        /// </summary>
        internal static string WarningSelectPanentNode {
            get {
                return ResourceManager.GetString("WarningSelectPanentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Winning_the_battle_against_Coronavirus {
            get {
                object obj = ResourceManager.GetObject("Winning_the_battle_against_Coronavirus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
